apiVersion: v1
kind: Service
metadata:
  name: user-frontend
  namespace: bikerental
  labels:
    app: bikerental
    component: user-frontend
spec:
  selector:
    app: bikerental
    component: user-frontend
  ports:
  - port: 80
    targetPort: 80
    name: http
  type: ClusterIP